task:
  name: macOS
  osx_instance:
    matrix:
      - image: monterey-base
  env:
    matrix:
      - PACKAGE: icu4c@72
      - PACKAGE: icu4c@71
  setup_script:
    - brew update
    - mkdir -p $(brew --repo)/Library/Taps/cirrus
    - ln -s $PWD $(brew --repo)/Library/Taps/cirrus/homebrew-testtap
    - brew tap --repair
  build_script:
    - brew install -v $install_opt cirrus/testtap/$PACKAGE
    - brew postinstall cirrus/testtap/$PACKAGE
    - brew audit --except=file,specs cirrus/testtap/$PACKAGE
    - brew test cirrus/testtap/$PACKAGE
